CC = wcl
CFLAGS = -fpi -d2 -mt -0
SRCS = RASTER~1.C
OBJS = $(SRCS:.c=.obj)
EXEC = RASTER~1.COM

$(EXEC): $(OBJS)
    $(CC) $(CFLAGS) $(OBJS)

.c.obj:
    $(CC) $(CFLAGS) -c $<

clean:
    del *.obj
    del *.com
