CC = wcl386
CFLAGS = -mf -3 -d2
SRCS = RASTER~1.C
OBJS = $(SRCS:.c=.obj)
EXEC = RASTER~1.EXE

$(EXEC): $(OBJS)
    $(CC) $(CFLAGS) $(OBJS)

.c.obj:
    $(CC) $(CFLAGS) -c $<

clean:
    del *.obj
    del *.exe
